/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-xpdf.h
 #	source generated by 4D Plugin Wizard
 #	Project : xpdf
 #	author : miyako
 #	2020/04/19
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_XPDF_H
#define PLUGIN_XPDF_H

#include "4DPluginAPI.h"

#include "C_TEXT.h"
#include "C_BLOB.h"

#include "aconf.h"

#include "4DPlugin-JSON.h"

#include <stdio.h>
#include <stdlib.h>
#include <stddef.h>
#include <string.h>

#include "gmem.h"
#include "gmempp.h"
#include "parseargs.h"
#include "GString.h"
#include "GlobalParams.h"
#include "Object.h"
#include "Stream.h"
#include "Array.h"
#include "Dict.h"
#include "XRef.h"
#include "Catalog.h"
#include "Page.h"
#include "PDFDoc.h"
#include "Error.h"
#include "config.h"

#include "TextOutputDev.h"
#include "ImageOutputDev.h"
#include "CharTypes.h"
#include "UnicodeMap.h"
#include "TextString.h"

#include "Zoox.h"

#include "SplashBitmap.h"
#include "Splash.h"
#include "SplashOutputDev.h"
#include "UTF8.h"

#include "png.h"

#include "fontconfig/fontconfig.h"

#pragma mark -

static void XPDF_Get_text(PA_PluginParameters params);
static void XPDF_Get_images(PA_PluginParameters params);
static void XPDF_Get_info(PA_PluginParameters params);

#endif /* PLUGIN_XPDF_H */
